NSERT INTO users
  (
  name, email, password)
VALUES
  ('John Smith', 'mrsmith@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
  ('Alex Guy', 'thatguy@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.'),
  ('Missie Robinson', 'robinson@gmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');

  INSERT INTO properties (
  title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code)
  VALUES (
  'Done game', 'Invented friendly longer circle agree today yet family trunk yard door noted chemical struck queen grandmother shelf at state command zulu from proper spoken powerful closely throat ability field went beside thought seat rock offer partly fair smooth announced even news carried habit film shells complex outer driven track are flag wise eager explain feature boy active proud thank writing due native last reason camera settle piece melted won draw was bark foreign given catch law minerals climb break mail force dawn pie rule simplest offer chance jump gold correctly lucky hit chemical new island start like gas loud create general group simple difficulty action back bean spend for telephone gentle there page tape position chapter oil tea fact sugar jungle receive ride poor join today soap belt jungle many wonderful difficulty swung cannot sale wear apartment gulf remove fresh somebody art hole third wash exercise jet development for giving health front knife underline source catch meat recent fifty band apartment father human bank shaking film education oxygen return greatly compass lion careful girl zebra building some function citizen eight noted die coming frequently dug day consonant phrase youth black exciting evidence influence floating blind behavior system vowel first telephone pretty thank shoulder north affect tail country track corn against middle valley found wing buried village station claws each fat birds ordinary coming felt square circle instance gold felt price themselves inside send smaller nation speed meet flew find flat tightly whenever rubber sick raise store left sunlight step appropriate cheese kill public come rhythm handsome couple bend ready locate take skill horn circle climb distant edge carried against one title among plates grade list burn enough refer sand government shadow mixture buy valuable frighten either parts early tone mill him tell moon never action yes respect believed seen whale', 69, 'https://images.pexels.com/photos/271649/pexels-photo-271649.jpeg', 'https://images.pexels.com/photos/271649/pexels-photo-271649.jpeg?auto=compress&cs=tinysrgb&h=350', 57597, 0, 1, 7, true, 'Prince Edward Island', 'Summerside', 'Canada', '1624 Cufpip Square', '79224');
  INSERT INTO properties (
  title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code)
  VALUES (
  'Prepare if', 'Angry pair does flame factory night sum party trip tomorrow none friend rain quickly generally grew bell row my stairs turn sang possibly having badly over bit inside six industry lonely scientific use he only as long feel instrument worth struggle almost material pilot good roar raw past chief describe join parts welcome feed figure trip settlers partly egg happily have forth bad percent join tobacco writing harder dream series shaking nuts wrong trap actual electric limited join deal hand tape know serve divide sky everyone we snow save mill engineer declared tea proper again earlier strange away aid yet total capital regular pride dream tape example hidden both sense possible earn increase environment area join sand pleasant made hungry throat safety such fighting fruit molecular event thread saw fall clay people stranger chose though citizen state value wild pitch want flower calm nervous silk lovely chosen transportation practice change what occur symbol else thank rose drew central needs proper great twice family shore sink pile clothes character song pocket public unusual chemical canal jar dug together track easily exist organization thou valley ants official accept wide shorter bottle nearby population highest seldom middle weigh anything strength allow guess wore pig cut price special neighborhood nature southern worry properly slow garage religious breath fix dog window human due hurt replied knife gather shop series see sunlight first girl western word vowel look shallow free shout specific alike bell positive deer donkey won union tobacco supper fence discuss seldom possible women science chamber perfect swam principal only elephant tone zero hold instance claws upper hide when anywhere told island aside brown town planet climate layers tribe elephant acres like aware nose jump advice extra thin first flight door stared machinery poetry season climb hand wheat wheat rising fog being tower brick', 184, 'https://images.pexels.com/photos/1027512/pexels-photo-1027512.jpeg', 'https://images.pexels.com/photos/1027512/pexels-photo-1027512.jpeg?auto=compress&cs=tinysrgb&h=350', 21137, 4, 7, 2, true, 'Ontario', 'Orillia', 'Canada', '1492 Ufimo Junction', '47597');
  INSERT INTO properties (
  title, description, owner_id, cover_photo_url, thumbnail_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, active, province, city, country, street, post_code)
  VALUES (
  'Roll stranger', 'Observe typical hit organization fruit thumb cost beat numeral chest careful character lose far tent meant thrown traffic movie use golden receive brain rod mood wooden children solve swung though spider smell box put importance afraid touch above smile would refer size good correctly blue duck hunt divide lack whenever further thus organization reach frozen furniture river claws threw catch uncle gray meant lips shout sister pack want trade active wrong value store plural alphabet to police agree make why honor decide rhyme rough new sale come putting remove noted castle object window bridge complete steam sort process opportunity replace basis method hour pine duty inside electricity think surprise go rice nearer fewer hearing soil bite water higher active continent solve beside muscle seeing develop general prize atom musical unusual active appearance cost bean structure zero bus series grew station word organization complete being think make price wish division thing furniture up depend means flew struck correctly paper pond courage brick mouse dull fill official clothes truth morning fun raise cave again wet military live best rhyme author screen afternoon completely should surface tired diameter seat want bare gift glass swim claws lucky highway service leather equal appropriate meat seat window day lady seeing sheet believed battle tax cannot pass universe happily biggest son surrounded generally wish slow loud indicate lead aboard riding pet package settlers blank substance moving golden condition human offer being spend nest iron anybody left play route poem research sky tree wear planet show none hill buy beauty equipment hearing fight type want report aboard consist lesson favorite involved fog toy clear prevent done occasionally grandmother nails shut no simplest block making fifteen trace husband rabbit reach slight classroom accurate fewer monkey shot contrast left pet weak package might sitting you thread pan week gift he', 650, 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg', 'https://images.pexels.com/photos/2099019/pexels-photo-2099019.jpeg?auto=compress&cs=tinysrgb&h=350', 5375, 2, 7, 3, true, 'Alberta', 'Edmonton', 'Canada', '1295 Gecado Point', '96594');


  INSERT INTO reservations (
  id, guest_id, property_id, start_date, end_date)
  VALUES (
  100999, 723, 104, '2022-09-31', '2022-10-16');



  INSERT INTO property_reviews (
  guest_id, property_id, reservation_id, rating, message)
  VALUES (
  831, 195, 1011943, 3, 'laurem ipsum');
  INSERT INTO property_reviews (
  guest_id, property_id, reservation_id, rating, message)
  VALUES (
  613, 333, 1016292, 4, 'laurem ipsum');
